### ISSUE TITLE
Integration tests are failing

### ISSUE THREAD

**Issue by jonnyarnold** [trussle/snowy-js-client#12]
Triggered by our [Renovate PR](https://github.com/trussle/snowy-js-client/pull/11), it turns out our [master build is currently failing](https://travis-ci.org/trussle/snowy-js-client/jobs/362515339).

**Comment by vickyyyyyyy** [comment]
Tests were fixed in this commit https://github.com/trussle/snowy-js-client/commit/47ec7fe47dacb2d55dc746c0ad067773541caeca
